version: '3'

services:
  taskmanager-api-nodejs:
    container_name: taskmanager-api-nodejs
    build:
      context: .
    environment:
      TZ: 'America/Sao_Paulo'
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    links:
      - taskmanager-api-mongo

  taskmanager-api-mongo:
    container_name: taskmanager-api-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: taskmanager_api
    ports:
      - 27017:27017
    volumes:
      - ./dbdata:/data/db
      - ./seed-data/tasks.js:/docker-entrypoint-initdb.d/tasks.js:ro
